[package]
name = "Background - The Vampire"
url = "https://www.nexusmods.com/morrowind/mods/52978"
authors = ["JosephMcKean"]
version = "1.0.1"

[dependencies]
assets = ["MWSE\\mods\\JosephMcKean\\vampBackground"]

[dependencies.mods."Merlord's Character Background"]
mwse-module = "mer.characterBackgrounds"
url = "https://www.nexusmods.com/morrowind/mods/46795"
